name: BentoBox-IslandFly
main: world.bentobox.islandfly.IslandFlyPladdon
version: ${project.version}${build.number}
api-version: "1.17"

authors: [tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
